// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/getupandgo/snooper-wooper/dao (interfaces: TokensDao)

// Package dao is a generated GoMock package.
package dao

import (
	models "github.com/getupandgo/snooper-wooper/models"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockTokensDao is a mock of TokensDao interface
type MockTokensDao struct {
	ctrl     *gomock.Controller
	recorder *MockTokensDaoMockRecorder
}

// MockTokensDaoMockRecorder is the mock recorder for MockTokensDao
type MockTokensDaoMockRecorder struct {
	mock *MockTokensDao
}

// NewMockTokensDao creates a new mock instance
func NewMockTokensDao(ctrl *gomock.Controller) *MockTokensDao {
	mock := &MockTokensDao{ctrl: ctrl}
	mock.recorder = &MockTokensDaoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockTokensDao) EXPECT() *MockTokensDaoMockRecorder {
	return m.recorder
}

// GetTopTokens mocks base method
func (m *MockTokensDao) GetTopTokens(arg0 uint64) ([]models.Token, error) {
	ret := m.ctrl.Call(m, "GetTopTokens", arg0)
	ret0, _ := ret[0].([]models.Token)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTopTokens indicates an expected call of GetTopTokens
func (mr *MockTokensDaoMockRecorder) GetTopTokens(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTopTokens", reflect.TypeOf((*MockTokensDao)(nil).GetTopTokens), arg0)
}

// SaveToken mocks base method
func (m *MockTokensDao) SaveToken(arg0 *models.Token) (*models.Token, error) {
	ret := m.ctrl.Call(m, "SaveToken", arg0)
	ret0, _ := ret[0].(*models.Token)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveToken indicates an expected call of SaveToken
func (mr *MockTokensDaoMockRecorder) SaveToken(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveToken", reflect.TypeOf((*MockTokensDao)(nil).SaveToken), arg0)
}
