version: '2'
services:
   
    database:
      container_name: snoop-db
      image: postgres:10
      restart: always
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
      ports:
        - "5432:5432"

    server:
      build: .
      restart: always
      depends_on:
        - database
      ports:
        - "8000:8000"
      volumes:
        - ./config:/config
      environment:
        - DB_HOST=database
        - DB_PORT=5432
        - HTTP_PORT=8000
        - GIN_MODE=release